= rhc:latest

This is a Fedora 22 based OpenShift Client tools, known as rhc,
container image. It's best used if you use some volumes with it.

It also includes Ruby on Rails 4.2, but no docs!

= Prerequisites

A host running docker, I prefere Fedora 22 on my laptop.

= Installation

Simple install the rhc container image from hub.docker.com by `docker
pull b4mad/rhc`

= Usage

= Copyright

Copyright (C) 2015 Christoph Görn 

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License
along with this program. If not, see <http://www.gnu.org/licenses/>.

The GNU Lesser General Public License is provided within the file
lgpl-3.0.txt.

